#define CONSTANT_DISTRIBUTION 1
#define UNIFORM_DISTRIBUTION 2
#define EXPONENTIAL_DISTRIBUTION 3


#define ARRIVAL_EVENT 1
#define DEPARTURE_EVENT 2
#define CONTEXT_SWITCH 3
#define TIME_SLICE_EXPIRE 4
#define TIME_OUT 5


#define FCFS 1
#define ROUND_ROBIN 2
